server:
  port: 8082

spring:
  application:
    name: Цифровой портал для репетиторов (сервис для работы с курсами)
    version: 1.0
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.default_schema: ${DB_SCHEMA}
  flyway:
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8
    default-schema: ${DB_SCHEMA}
    schemas: ${DB_SCHEMA}
    create-schemas: true

springdoc:
  api-docs:
    path: /teacher-portal/courses-service/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
  paths-to-match:
    - /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

integration:
  user:
#    host: http://razum0ff.ru:8081
#    host: http://localhost:8081
    host: ${USER_SERVICE_HOST:http://razum0ff.ru:8081}
    get-user-profiles: /api/user/profiles

jwt:
  secret: ${JWT_SECRET_KEY:ajscqSVPNj4GNzF+Ln2H6yaE2etWGExa618+TDP96ZE=}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:300000} # 300000
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${USERNAME_MINIO:minio}
  secret-key: ${PASSWORD_MINIO:minio123}
  bucket-name: ${BUCKET_NAME:bucket-name-images}

origins:
  front: ${FRONT_ORIGIN:http://localhost:3000}